#!/bin/bash
set -euo pipefail

function join { local IFS="$1"; shift; echo "$*"; }

bin_dir=${BIN_DIR:-/opt}
app_parts=(${_HANDLER//\// })
lib_dir=${LIB_DIR:-lib}
libs=$(join : $(find "$bin_dir/$lib_dir" $lib_dir -name '*.jar' 2>/dev/null))
classpath=".:${bin_dir}:${libs:-.}"

"$bin_dir/lumo" --classpath "$classpath" -e "(require (quote ${app_parts[0]}))" -m runtime
